#не забудь поменять название хоста и провреить адрес локи
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.20.96:3100/loki/api/v1/push

scrape_configs:
  - job_name: systemd_journal
    journal:
      max_age: 24h
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'service_name'
      - replacement: "linux_agents.191:9080"
        target_label: "host"

  - job_name: docker.191
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - replacement: "linux_agents.191:9080"
        target_label: "host"
