version: '3'

services:
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    environment:
      HOST: "grafana.96"
    ports:
      - "9080:9080"
      - "3100:3100"  
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    command: ["--collector.systemd"]
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
